runtime: nodejs
env: flex
env_variables:
  FIREBASE_API_KEY: "AIzaSyDV7lnBOhAucGoJZdY_m6IqdMXAs6buyB8"
  FIREBASE_AUTH_DOMAIN: "stc-toolkit.firebaseapp.com"
  FIREBASE_DB_URL: "https://stc-toolkit.firebaseio.com"
  FIREBASE_PROJECT_ID: "stc-toolkit"
  FIREBASE_STORAGE_BUCKET: ""
  FIREBASE_MESSAGING_SENDER_ID: "117348823057"